---
networks:
  geoserver_postgis: ~
services:
  geoserver:
    image: bioatlas/ala-geoserver:v0.4
    container_name: geoserver
    environment:
      - JAVA_OPTS=-Xmx1g -Xms128m -Xss256k -Djava.awt.headless=true
    env_file: ./env/geoserver/.envgeoserver
    volumes:
      - /data/geoserver_data_dir:/data/geoserver_data_dir
      - /data/spatial-data:/data/spatial-data
    networks:
      - geoserver_postgis
    ports:
      - "8079:8080"
  postgis:
    image: mdillon/postgis:9.6-alpine
    container_name: postgis
    networks:
      - geoserver_postgis
    ports:
      - "5432:5432"
    volumes:
      - /data/spatial-db:/data/spatial-db
      - ./env/postgis/pg_hba.conf:/etc/postgresql/9.6/main/pg_hba.conf
      - ./env/postgis/layersdb.sql:/docker-entrypoint-initdb.d/layersdb.sql
#volumes:
#  data_geoserver:
#  data_spatialservice:
#  db_data_postgis:
version: "2"
